module.exports = {
    _embedded: {
        limeobjects: [
            {
                fi: 'Luodaanko "%1" tarjouksen seuraamista varten?',
                formtag: '<localize owner="ControlsHandlerDeal" code="q_create_quotation"/>',
                no: 'Vil du opprette en "%1", for å følge opp tilbudet?',
                code: 'q_create_quotation',
                _createduser: 1,
                _id: 1001,
                context: 'Fråga om användaren vill skapa upp en ny Att-göra när status på affären har sats till Offert.',
                aplocalizecode: 'localize.ControlsHandlerDeal.q_create_quotation',
                sv: 'Vill du skapa en "%1" för att följa upp offerten?',
                _timestamp: '2016-02-08T16:30:52.870000+01:00',
                _updateduser: 2901,
                da: 'Vil du oprette et "%1" for at følge op på tilbudet?',
                _descriptive: '1001',
                lookupcode: 'Localize.GetText("ControlsHandlerDeal", "q_create_quotation")',
                _createdtime: '2011-10-31T11:47:50.593000+01:00',
                _links: {
                    limetype: {
                        href: 'https://prostaging/core54/api/v1/limetype/localize/',
                        name: 'localize',
                    },
                    self: {
                        href: 'https://prostaging/core54/api/v1/limeobject/localize/1001/',
                    },
                },
                owner: 'ControlsHandlerDeal',
                en_us: 'Do you want to create a "%1", for doing a follow up on the quote?',
            },
            {
                fi: 'Seuraa tarjousta',
                formtag: '<localize owner="ControlsHandlerDeal" code="quotation_followup"/>',
                no: 'Følg opp tilbudet',
                code: 'quotation_followup',
                _createduser: 1,
                _id: 1002,
                context: 'Text som sätts på att-göra uppgiften som skapar upp när status sätts till offert.',
                aplocalizecode: 'localize.ControlsHandlerDeal.quotation_followup',
                sv: 'Följ upp offert',
                _timestamp: '2016-02-08T16:31:07.443000+01:00',
                _updateduser: 2901,
                da: 'Følg op på tilbud',
                _descriptive: '1002',
                lookupcode: 'Localize.GetText("ControlsHandlerDeal", "quotation_followup")',
                _createdtime: '2011-10-31T12:22:30.227000+01:00',
                _links: {
                    limetype: {
                        href: 'https://prostaging/core54/api/v1/limetype/localize/',
                        name: 'localize',
                    },
                    self: {
                        href: 'https://prostaging/core54/api/v1/limeobject/localize/1002/',
                    },
                },
                owner: 'ControlsHandlerDeal',
                en_us: 'Follow up quote',
            },
            {
                fi: 'Tehtävä on merkitty suoritetuksi.',
                formtag: '<localize owner="Actionpad_Todo" code="e_already_done"/>',
                no: 'Oppgaven har allerede blitt markert som utført',
                code: 'e_already_done',
                _createduser: 1,
                _id: 1005,
                context: 'Kontroll innan man prickar av en post om den redan är avprickad',
                aplocalizecode: 'localize.Actionpad_Todo.e_already_done',
                sv: 'Att göra uppgiften har redan prickats av.',
                _timestamp: '2014-03-13T21:49:32.527000+01:00',
                _updateduser: 1,
                da: 'Opgaven er allerede afsluttet.',
                _descriptive: '1005',
                lookupcode: 'Localize.GetText("Actionpad_Todo", "e_already_done")',
                _createdtime: '2011-10-31T12:40:06.730000+01:00',
                _links: {
                    limetype: {
                        href: 'https://prostaging/core54/api/v1/limetype/localize/',
                        name: 'localize',
                    },
                    self: {
                        href: 'https://prostaging/core54/api/v1/limeobject/localize/1005/',
                    },
                },
                owner: 'Actionpad_Todo',
                en_us: 'The Todo has already been marked as done.',
            },
            {
                fi: "Linkitetäänkö '%1' historiamerkintääsi?",
                formtag: '<localize owner="Actionpad_Company" code="q_connect_person"/>',
                no: "Ønsker du å koble '%1' til din historikk notering?",
                code: 'q_connect_person',
                _createduser: 1,
                _id: 1007,
                context: 'När man skapar en ny historikpost så ställs denna fråga om den i personlistan markerade personen skall kopplas till historikposten',
                aplocalizecode: 'localize.Actionpad_Company.q_connect_person',
                sv: "Vill du koppla '%1' till din historikpost?",
                _timestamp: '2014-03-13T21:49:32.527000+01:00',
                _updateduser: 1,
                da: "Vil du knytte '%1' til din historikken?",
                _descriptive: '1007',
                lookupcode: 'Localize.GetText("Actionpad_Company", "q_connect_person")',
                _createdtime: '2011-10-31T12:50:46.960000+01:00',
                _links: {
                    limetype: {
                        href: 'https://prostaging/core54/api/v1/limetype/localize/',
                        name: 'localize',
                    },
                    self: {
                        href: 'https://prostaging/core54/api/v1/limeobject/localize/1007/',
                    },
                },
                owner: 'Actionpad_Company',
                en_us: "Do you wish to link '%1' to your history note?",
            },
            {
                fi: 'Tehtävä on merkitty suoritetuksi. Haluatko ottaa sen uudelleen käsittelyyn?',
                formtag: '<localize owner="ActionPad_Helpdesk" code="q_done_reopen"/>',
                no: 'Denne saken er markert som utført, vil du gjenoppta saken?',
                code: 'q_done_reopen',
                _createduser: 1,
                _id: 1008,
                context: 'Fråga om man vill öppna ett ärende igen då man försöker Ta det.',
                aplocalizecode: 'localize.ActionPad_Helpdesk.q_done_reopen',
                sv: 'Ärendet är avprickat, vill du återuppta ärendet?',
                _timestamp: '2014-03-13T21:49:32.527000+01:00',
                _updateduser: 1,
                da: 'Sagen står som afsluttet, vil du genåbne sagen?',
                _descriptive: '1008',
                lookupcode: 'Localize.GetText("ActionPad_Helpdesk", "q_done_reopen")',
                _createdtime: '2011-11-01T21:12:34.440000+01:00',
                _links: {
                    limetype: {
                        href: 'https://prostaging/core54/api/v1/limetype/localize/',
                        name: 'localize',
                    },
                    self: {
                        href: 'https://prostaging/core54/api/v1/limeobject/localize/1008/',
                    },
                },
                owner: 'ActionPad_Helpdesk',
                en_us: 'The case is checked off, do you want to resume the errand?',
            },
            {
                fi: 'Sinut on jo merkitty vastuulliseksi tehtävään.',
                formtag: '<localize owner="ActionPad_Helpdesk" code="i_already_responsible"/>',
                no: 'Du er allerede satt som ansvarlig for saken',
                code: 'i_already_responsible',
                _createduser: 1,
                _id: 1009,
                context: 'Informationsmeddelande om att man har försökt ta ett ärende som man redan är ansvarig för',
                aplocalizecode: 'localize.ActionPad_Helpdesk.i_already_responsible',
                sv: 'Du är redan satt som ansvarig för ärendet.',
                _timestamp: '2015-04-20T11:14:13.610000+02:00',
                _updateduser: 2901,
                da: 'Du er allerede ansvarlige på sagen.',
                _descriptive: '1009',
                lookupcode: 'Localize.GetText("ActionPad_Helpdesk", "i_already_responsible")',
                _createdtime: '2011-11-01T21:15:16.697000+01:00',
                _links: {
                    limetype: {
                        href: 'https://prostaging/core54/api/v1/limetype/localize/',
                        name: 'localize',
                    },
                    self: {
                        href: 'https://prostaging/core54/api/v1/limeobject/localize/1009/',
                    },
                },
                owner: 'ActionPad_Helpdesk',
                en_us: 'You are already appointed as responsible for the case.',
            },
            {
                fi: "Tehtävän vastuuhenkilöksi on merkitty '%1'. Haluatko ottaa tehtävän vastuullesi?",
                formtag: '<localize owner="ActionPad_Helpdesk" code="q_take_over"/>',
                no: "Denne saken er allerede tatt av '%1'. Ønsker du å ta over ansvaret for denne saken?",
                code: 'q_take_over',
                _createduser: 1,
                _id: 1010,
                context: 'Fråga om man vill ta över ett ärende efter att ha tryck i Actionpadden.',
                aplocalizecode: 'localize.ActionPad_Helpdesk.q_take_over',
                sv: "Ärendet är redan taget av '%1'. Vill du ta över ärendet?",
                _timestamp: '2017-02-01T15:43:51.360000+01:00',
                _updateduser: 1,
                da: "Sagen er taget af '%1'. Vil du overtage sagen?",
                _descriptive: '1010',
                lookupcode: 'Localize.GetText("ActionPad_Helpdesk", "q_take_over")',
                _createdtime: '2011-11-01T21:20:16.407000+01:00',
                _links: {
                    limetype: {
                        href: 'https://prostaging/core54/api/v1/limetype/localize/',
                        name: 'localize',
                    },
                    self: {
                        href: 'https://prostaging/core54/api/v1/limeobject/localize/1010/',
                    },
                },
                owner: 'ActionPad_Helpdesk',
                en_us: "The case is already taken by '%1'. Do you want to take over the errand?",
            },
            {
                fi: 'Tehtävä on aloitettu.',
                formtag: '<localize owner="ActionPad_Helpdesk" code="t_errand_started"/>',
                no: 'Saken ble startet',
                code: 't_errand_started',
                _createduser: 1,
                _id: 1011,
                context: 'Text som skrivs på den historikpost som skapas då man påbörjar ett ärende',
                aplocalizecode: 'localize.ActionPad_Helpdesk.t_errand_started',
                sv: 'Ärendet påbörjades.',
                _timestamp: '2015-04-20T11:14:32.870000+02:00',
                _updateduser: 2901,
                da: 'Sagen påbegyndtes.',
                _descriptive: '1011',
                lookupcode: 'Localize.GetText("ActionPad_Helpdesk", "t_errand_started")',
                _createdtime: '2011-11-01T21:23:32.330000+01:00',
                _links: {
                    limetype: {
                        href: 'https://prostaging/core54/api/v1/limetype/localize/',
                        name: 'localize',
                    },
                    self: {
                        href: 'https://prostaging/core54/api/v1/limeobject/localize/1011/',
                    },
                },
                owner: 'ActionPad_Helpdesk',
                en_us: 'The case was started.',
            },
            {
                fi: 'Tehtävä on otettu käsittelyyn.',
                formtag: '<localize owner="ActionPad_Helpdesk" code="t_errand_restarted"/>',
                no: 'Saken ble gjenopptatt',
                code: 't_errand_restarted',
                _createduser: 1,
                _id: 1012,
                context: 'Text som skrivs på den historikpost som skapas då man återupptar ett ärende',
                aplocalizecode: 'localize.ActionPad_Helpdesk.t_errand_restarted',
                sv: 'Ärendet återupptogs.',
                _timestamp: '2015-04-20T11:14:42.417000+02:00',
                _updateduser: 2901,
                da: 'Sagen blev genåbnet.',
                _descriptive: '1012',
                lookupcode: 'Localize.GetText("ActionPad_Helpdesk", "t_errand_restarted")',
                _createdtime: '2011-11-01T21:24:36.197000+01:00',
                _links: {
                    limetype: {
                        href: 'https://prostaging/core54/api/v1/limetype/localize/',
                        name: 'localize',
                    },
                    self: {
                        href: 'https://prostaging/core54/api/v1/limeobject/localize/1012/',
                    },
                },
                owner: 'ActionPad_Helpdesk',
                en_us: 'The case was resumed.',
            },
            {
                fi: 'Tehtävä otettu haltuun.',
                formtag: '<localize owner="ActionPad_Helpdesk" code="t_errand_overtaken"/>',
                no: 'Saken ble overtatt',
                code: 't_errand_overtaken',
                _createduser: 1,
                _id: 1013,
                context: 'Text som skrivs på den historikpost som skapas då man tar över ett ärende',
                aplocalizecode: 'localize.ActionPad_Helpdesk.t_errand_overtaken',
                sv: 'Ärendet övertogs',
                _timestamp: '2017-02-01T15:43:22.617000+01:00',
                _updateduser: 1,
                da: 'Sagen blev overtaget.',
                _descriptive: '1013',
                lookupcode: 'Localize.GetText("ActionPad_Helpdesk", "t_errand_overtaken")',
                _createdtime: '2011-11-01T21:26:56.177000+01:00',
                _links: {
                    limetype: {
                        href: 'https://prostaging/core54/api/v1/limetype/localize/',
                        name: 'localize',
                    },
                    self: {
                        href: 'https://prostaging/core54/api/v1/limeobject/localize/1013/',
                    },
                },
                owner: 'ActionPad_Helpdesk',
                en_us: 'The case was taken over.',
            },
        ],
    },
    _links: {
        self: {
            href: 'https://prostaging/core54/api/v1/limeobject/localize/?_limit=10',
        },
    },
}
