// This file is generated by genenum.js. Don't modify.
// Source: c:\src\lime\src\lime.idl

// OverviewStateEnum
	var lkOverviewStateVisible = 1;
	var lkOverviewStateActive = 2;

// InspectorSectionStateEnum
	var lkInspectorSectionStateNormal = 0;
	var lkInspectorSectionStateCollapsed = 1;

// InspectorSectionTypeEnum
	var lkInspectorSectionTypeNormal = 0;
	var lkInspectorSectionTypeCollapsable = 1;

// LookupCommandButtonEnum
	var lkLookupCommandButtonUnspecified = 0;
	var lkLookupCommandButtonByIndex = 1;
	var lkLookupCommandButtonByID = 2;
	var lkLookupCommandButtonByText = 3;

// LookupPopupEnum
	var lkLookupPopupUnspecified = 0;
	var lkLookupPopupByName = 1;

// ShowPopupEnum
	var lkShowPopupNormal = 1;
	var lkShowPopupNoActivate = 4;

// PopupStyleEnum
	var lkPopupStyleNone = 0x00;
	var lkPopupStyleTopMostWindow = 0x01;
	var lkPopupStyleToolWindow = 0x02;
	var lkPopupStyleSizeableWindow = 0x04;
	var lkPopupStyleTaskBarWindow = 0x08;
	var lkPopupStyleTransparentWindow = 0x10;
	var lkPopupStyleMinimizeBox = 0x20;
	var lkPopupStyleMaximizeBox = 0x40;

// LookupMenuItemEnum
	var lkLookupMenuItemUnspecified = 0;
	var lkLookupMenuItemByIndex = 1;
	var lkLookupMenuItemByID = 2;
	var lkLookupMenuItemByName = 3;

// InspectorModeEnum
	var lkInspectorModeNone = 0;
	var lkInspectorModeEdit = 1;
	var lkInspectorModeNew = 2;

// PaneStyleEnum
	var lkPaneStyleDefault = 0;
	var lkPaneStylePersistentURL = 1;
	var lkPaneStyleRestrictedBrowsing = 2;
	var lkPaneStyleNoToolBar = 4;
	var lkPaneStyleCustomControl = 8;

// LoginEnum
	var lkLoginUnspecified		= 0x0000;
	var lkLoginLocalServer		= 0x0001;
	var lkLoginRemoteServer		= 0x0002;
	var lkLoginProtocolHttp		= 0x0004;
	var lkLoginProtocolNetTcp	= 0x0008;

// OpenInspectorEnum
	var lkActivateExisting = 0x0001;
	var lkNoActivate = 0x0002;

// DialogTypeEnum
	var lkDialogUnspecified = -1;
	var lkDialogAbout = 0;
	var lkDialogField = 1;
	var lkDialogFields = 2;
	var lkDialogView = 3;
	var lkDialogViews = 4;
	var lkDialogFilter = 5;
	var lkDialogFilters = 6;
	var lkDialogReports = 7;
	var lkDialogCopySpecial = 8;
	var lkDialogUpdateField = 9;
	var lkDialogDocumentInfo = 10;
	var lkDialogHTML = 11;
	var lkDialogSelectField = 12;
	var lkDialogSearchRecords = 13;
	var lkDialogDataTemplate = 14;
	var lkDialogGoto = 15;
	var lkDialogImportContacts = 16;
	var lkDialogUpdateTab = 17;

// MoveTypeEnum
	var lkMoveFirst = 0;
	var lkMoveLast = 1;
	var lkMoveNext = 2;
	var lkMovePrevious = 3;

// ObjectSelectionType
	var lkCurrent = 0;
	var lkSelected = 1;
	var lkAll = 2;

// ButtonBarPositionEnum
	var lkButtonBarLeft = 0;
	var lkButtonBarRight = 1;
	var lkButtonBarTop = 2;
	var lkButtonBarBottom = 3;
	var lkButtonBarFloating = 4;

// WindowState
	var lkWindowStateMaximized = 0;
	var lkWindowStateMinimized = 1;
	var lkWindowStateNormal = 2;

// ListSelectionType
	var lkSelectionOff = 0;
	var lkSelectionOn = 1;
	var lkSelectionInvert = 2;

// MailerFlagsEnum
	var lkMailerFlagUnspecified = 0;
	var lkMailerFlagPreview = 1;
	var lkMailerFlagSuppressSave = 2;
	var lkMailerFlagAlwaysSave = 4;

// MailerSupportsEnum
	var lkMailerSupportsTemplates = 1;
	var lkMailerSupportsMailerDocument = 2;

// MailerRecipientTypeEnum
	var lkMailerRecipientTypeOriginator = 0;
	var lkMailerRecipientTypeTo = 1;
	var lkMailerRecipientTypeCC = 2;
	var lkMailerRecipientTypeBC = 3;

// CreateUrlTypeEnum
	var lkCreateUrlTypeLink = 0;
	var lkCreateUrlTypeFile = 1;

// MessengerSupportsEnum
	var lkMessengerSupportsClass = 0;
	var lkMessengerSupportsDocument = 1;
	var lkMessengerSupportsCancelSend = 2;

// LookupMessengerFactoryEnum
	var lkLookupMessengerFactoryUnspecified = 0;
	var lkLookupMessengerFactoryByName = 1;
	var lkLookupMessengerFactoryByLocalName = 2;

// ExplorerStateEnum
	var lkExplorerStateNone = 0x0000;
	var lkExplorerStateRequeryRequired = 0x0001;
	var lkExplorerStateRecordEdit = 0x0002;

// ExplorerStyleEnum
	var lkExplorerStyleDefault = 0x0000;
	var lkExplorerStyleMultiSelect = 0x0001;
	var lkExplorerStyleMultiLine = 0x0002;
	var lkExplorerStyleStriped = 0x0004;
	var lkExplorerStyleAllowEdit = 0x0008;
	var lkExplorerStyleGrid = 0x0010;
	var lkExplorerStyleFooter = 0x0020;
	var lkExplorerStyleLinkClick = 0x0040;
	var lkExplorerStyleCheckBoxClick = 0x0080;

// SelectEnum
	var lkSelectOn = 0;
	var lkSelectOff = 1;
	var lkSelectInvert = 2;

// ExportFormatEnum
	var lkExportFormatUnspecified = 0x0000;
	var lkExportFormatText = 0x0001;
	var lkExportFormatUnicodeText = 0x0002;
	var lkExportFormatHTML = 0x0003;
	var lkExportFormatIncludeFieldNames = 0x1000;

// LookupExplorerItemEnum
	var lkLookupExplorerItemUnspecified = 0;
	var lkLookupExplorerItemByIndex = 1;
	var lkLookupExplorerItemByID = 2;

// DropSupportsEnum
	var lkDropSupportsExplorer = 0x1;
	var lkDropSupportsExtension = 0x2;

// LookupControlEnum
	var lkLookupControlUnspecified = 0;
	var lkLookupControlByName = 1;

// ControlsStateEnum
	var lkControlsStateNone = 0x0000;
	var lkControlsStateNew = 0x0001;
	var lkControlsStateModified = 0x0002;
	var lkControlsStateDeleted = 0x0004;

// ControlCommandEnum
	var lkControlCommandSearchDialog = 1;
	var lkControlCommandNew = 2;
	var lkControlCommandUnlink = 3;
	var lkControlCommandSearch = 4;
	var lkControlCommandContextMenu = 5;
	var lkControlCommandLink = 6;
	var lkControlCommandSuggestValue = 7;
	var lkControlCommandDropDown = 8;
	var lkControlCommandOpen = 9;
	var lkControlCommandAdd = 10;
	var lkControlCommandDelete = 11;

// LinkControlStyleEnum
	var lkLinkControlStyleContext = 0;
	var lkLinkControlStyleDisableNew = 1;
	var lkLinkControlStyleDisableOpen = 2;
	var lkLinkControlStyleDisableSearch = 4;
	var lkLinkControlStyleDisableUnlink = 8;
	var lkLinkControlStyleDisableDelete = 16;
	var lkLinkControlStyleDisableShowAll = 32;
	var lkLinkControlStyleDropDown = 64;

// ResourceTypeEnum
	var lkResourceTypeAll = 0;
	var lkResourceTypeLanguage = 1;
	var lkResourceTypeIniFile = 2;

// HelpCommandEnum
	var lkHelpDisplayTopic = 0x0000;
	var lkHelpDisplayTableOfContents = 0x0001;
	var lkHelpDisplayIndex = 0x0002;
	var lkHelpContext = 0x000;

// CampaignWizardModeEnum
	var lkCampaignModeUnspecified = 0;
	var lkCampaignModeNew = 1;
	var lkCampaignModeParticipantNew = 2;
	var lkCampaignModeParticipantEdit = 3;
	var lkCampaignModeParticipantDelete = 4;
	var lkCampaignModeParticipantNewSearch = 5;

