name: Build LBS

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install and build
      run: |
        npm install
        npm run build
    - name: setup semantic release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npm install -g semantic-release/semantic-release#master
        zip -r LBS dist VBA 
        semantic-release
 
