name: github pages

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: install
      uses: jefftriplett/python-actions@master
      if: github.event.deleted == false
      with:
        args: pip install -r ./docs/requirements.txt
    - name: build
      uses: jefftriplett/python-actions@master
      with:
        args: mkdocs build
    - name: deploy
      uses: peaceiris/actions-gh-pages@v1.1.0
      if: success()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./site
