name: Test PRs of LBS

on:
  pull_request:
    branches:
    - master

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install, test and build
      run: |
        npm install
        npm run test
        npm run build
 
